version: '3.8'

services:
  alpha_crm_db:
    image: postgres:17-alpine
    container_name: Alpha_CRM_DB
    restart: unless-stopped
    environment:
      POSTGRES_USER: alpha_crm_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: alpha_crm_db
      TZ: America/Costa_Rica
      PGTZ: America/Costa_Rica
    ports:
      - "3001:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./init-scripts:/docker-entrypoint-initdb.d 
    networks:
      - alpha_crm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alpha_crm_admin -d alpha_crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  alpha_crm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Alpha_CRM
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Usar el nombre del servicio de DB en lugar de localhost
      - DATABASE_URL=postgresql://alpha_crm_admin:${POSTGRES_PASSWORD}@alpha_crm_db:5432/alpha_crm_db
      - NODE_ENV=development
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TZ=${TZ}
    depends_on:
      alpha_crm_db:
        condition: service_healthy
    networks:
      - alpha_crm_network
    volumes:
      - ./uploads:/app/uploads
      # Para desarrollo, montar el código fuente
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local
    name: alpha_crm_postgres_data

networks:
  alpha_crm_network:
    driver: bridge
    name: alpha_crm_network